CREATE TABLE bot_state (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    running BOOLEAN NOT NULL DEFAULT FALSE,
    strategy VARCHAR(50) NOT NULL DEFAULT 'volatility_breakout',
    tickers VARCHAR(500) NOT NULL DEFAULT 'KRW-BTC',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
